CREATE DATABASE CAR_RENTAL_MANAGEMENT3;
USE CAR_RENTAL_MANAGEMENT3;

CREATE TABLE CUSTOMER (
CUSTOMER_NATIONAL_ID INT PRIMARY KEY ,
CUST_FNAME VARCHAR(50) NOT NULL,
CUST_LNAME VARCHAR(50) NOT NULL,
EMAIL VARCHAR(100),
PHONE VARCHAR(20),
WORK_PHONE VARCHAR(20),
PHYS_ADDRESS VARCHAR(50),
CITY VARCHAR(100),
COUNTRY VARCHAR(100),
IS_VERIFIED BOOL,
LICENSE_NO VARCHAR(50) NULL, 
PASSWWORD_HASH VARCHAR (255),
CREATED_AT DATE,
UPDATED_AT DATE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE NEXT_OF_KIN (
    CUSTOMER_NATIONAL_ID INT PRIMARY KEY ,
    FNAME VARCHAR(100) NOT NULL,
    LNAME VARCHAR(100) NOT NULL,
    PHYS_ADDRESS VARCHAR(255),
    PHONE VARCHAR(20),
    FOREIGN KEY (CUSTOMER_NATIONAL_ID) REFERENCES CUSTOMER(CUSTOMER_NATIONAL_ID)
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE BOOKED_VEHICLE (
    RSV_ID INT PRIMARY KEY AUTO_INCREMENT,
    CUSTOMER_NATIONAL_ID INT NOT NULL,
    VEHICLE_ID INT NOT NULL,
    PICKUP_DATE DATETIME,
    RETURN_DATE DATETIME,
    DATE_BOOKED DATETIME,
    EXPIRY_DATE DATETIME,
    FOREIGN KEY (CUSTOMER_NATIONAL_ID) REFERENCES CUSTOMER(CUSTOMER_NATIONAL_ID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (VEHICLE_ID) REFERENCES VEHICLE(VEHICLE_ID)
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE RECEIPT (
    RECEIPT_ID INT PRIMARY KEY AUTO_INCREMENT,
    PAY_ID INT NOT NULL,
    RSV_ID INT NOT NULL, -- foreignkey
    VEHICHLE_DESCRIPTION VARCHAR(50),
    FOREIGN KEY (PAY_ID) REFERENCES PAYMENT(PAY_ID)
        ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE RENT (
    EMP_ID INT PRIMARY KEY AUTO_INCREMENT,
    ACCOUNT VARCHAR(50),
    EMP_NAME VARCHAR(100),
    LOCATION VARCHAR(100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE EMPLOYEE (
    EMP_ID INT PRIMARY KEY AUTO_INCREMENT,
    EMP_NAME VARCHAR(100) NOT NULL,
    ROLE VARCHAR(50),
    EMAIL VARCHAR(100),
    PHONE VARCHAR(20)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE VEHICLE (
    VEHICLE_ID INT PRIMARY KEY AUTO_INCREMENT,
    BRAND VARCHAR(50),
    MAKE VARCHAR(50),
    MODEL VARCHAR(50),
    YEAR INT,
    PLATE_NUMBER VARCHAR(20) UNIQUE,
    TYPE VARCHAR(30),
    V_CONDITION VARCHAR(50),
    CATEGORY VARCHAR(50),
    VEHICLE_STATUS varchar(50) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE RENTAL (
    RENTAL_ID INT PRIMARY KEY AUTO_INCREMENT,
    PURPOSE VARCHAR(100),
    START_DATE DATETIME,
    EX_RETURN_DATE DATETIME,
    MILEAGE_ACCESSORY VARCHAR(255),
    VEHICLE_ID INT NOT NULL,
    CUSTOMER_NATIONAL_ID INT NOT NULL,
    EMP_ID INT NOT NULL,
    RNV_ID INT,
    FOREIGN KEY (VEHICLE_ID) REFERENCES VEHICLE(VEHICLE_ID)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (CUSTOMER_NATIONAL_ID) REFERENCES CUSTOMER(CUSTOMER_NATIONAL_ID)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (EMP_ID) REFERENCES RENT(EMP_ID)
        ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;	

CREATE TABLE PAYMENT (
    PAY_ID INT PRIMARY KEY AUTO_INCREMENT,
    PAY_NO VARCHAR(50),
    AMOUNT DECIMAL(10, 2),
    DATE DATE,
    ACC_NO VARCHAR(50),
    EMP_ID INT NOT NULL,
    FOREIGN KEY (EMP_ID) REFERENCES RENT(EMP_ID)
        ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE RE_TURN (
    RETURN_ID INT PRIMARY KEY AUTO_INCREMENT,
    COMMENTS TEXT,
    ACTUAL_DATE DATETIME,
    IS_LATE BOOL,
    RENTAL_ID INT NOT NULL,
    FOREIGN KEY (RENTAL_ID) REFERENCES RENTAL(RENTAL_ID)
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE LATE_RETURN (
    RETURN_ID INT NOT NULL,
    COMMENTS TEXT,
    HRS_LATE INT,
    PRIMARY KEY (RETURN_ID),
    FOREIGN KEY (RETURN_ID) REFERENCES RE_TURN(RETURN_ID)
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `license` (
  `License_No` varchar(50) NOT NULL,
  `Cust_National_ID` varchar(20) NOT NULL,
  `Front_Img_URL` varchar(255) DEFAULT NULL,
  `Back_Img_URL` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE VEHICLE
    ADD COLUMN SEATS        INT          NULL AFTER IMAGE_URL,
    ADD COLUMN TRANSMISSION VARCHAR(20)  NULL AFTER SEATS,
    ADD COLUMN FUEL_TYPE    VARCHAR(20)  NULL AFTER TRANSMISSION,
    ADD COLUMN ENGINE       VARCHAR(30)  NULL AFTER FUEL_TYPE,
    ADD COLUMN MILEAGE      VARCHAR(50)  NULL AFTER ENGINE,
    ADD COLUMN DRIVE_TYPE   VARCHAR(10)  NULL AFTER MILEAGE,
    ADD COLUMN FEATURES     TEXT         NULL AFTER DRIVE_TYPE;
    
    ALTER TABLE VEHICLE
    ADD COLUMN IMAGE_URL        INT          NULL AFTER VEHICLE_STATUS;
    
